version: "3.3"

services:
  nginx:
    image: nginx
    depends_on:
      - bitwarden
      - linkace
      - portainer
      - silverstrike
      - syncthing
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
    ports:
      - 80:80
      - 443:443

  silverstrike:
    image: simhnna/silverstrike
    depends_on:
      - silverstrike-db
    environment:
      ALLOWED_HOSTS: '*'
      DATABASE_URL: postgres://${SILVERSTRIKE_DB_USER}:${SILVERSTRIKE_DB_PASS}@silverstrike-db/${SILVERSTRIKE_DB_NAME}
      SECRET_KEY: ${SILVERSTRIKE_SECRET_KEY}

  silverstrike-db:
    image: postgres:10.3
    environment:
      POSTGRES_DB: ${SILVERSTRIKE_DB_NAME}
      POSTGRES_USER: ${SILVERSTRIKE_DB_USER}
      POSTGRES_PASSWORD: ${SILVERSTRIKE_DB_PASS}
    volumes:
      - /opt/silverstrike-data:/var/lib/postgresql/data

  linkace:
    image: linkace/linkace:php-nginx
    depends_on:
      - linkace-db
    expose:
      - 8080
    volumes:
      - ./.env-linkace:/app/.env
      - ./nginx-linkace.conf:/opt/docker/etc/nginx/conf.d/linkace.conf:ro
      - linkace-logs:/app/storage/logs

  linkace-db:
    image: bitnami/mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: ${LINKACE_DB_PASS_ROOT}
      MARIADB_USER: ${LINKACE_DB_USER}
      MARIADB_PASSWORD: ${LINKACE_DB_PASS}
      MARIADB_DATABASE: ${LINKACE_DB_NAME}
    volumes:
      - linkace-db:/bitnami

  portainer:
    image: portainer/portainer-ce
    expose:
      - 9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  bitwarden:
    image: bitwardenrs/server
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
    expose:
      - 3012
    volumes:
      - bw-data:/data

  syncthing:
    image: linuxserver/syncthing:version-v1.13.1
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
      UMASK_SET: "022"
    expose:
      - 8384
    volumes:
      - syncthing-config:/config
      - /home/ivanm/Sync:/data
    ports:
      - 22000:22000
      - 21027:21027/udp

volumes:
  bw-data:
  linkace-logs:
  linkace-db:
  portainer-data:
  syncthing-config:
