version: "3.3"

services:
  nginx:
    image: nginx
    depends_on:
      - syncthing
      - bitwarden
      - ffsync
      - wikijs
    networks:
      - front
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
    ports:
      - 80:80
      - 443:443

  syncthing:
    image: linuxserver/syncthing:v1.4.0-ls28
    container_name: syncthing
    networks:
      front:
    environment:
      PUID: "1001"
      PGID: "1001"
      TZ: "Europe/London"
      UMASK_SET: "022"
    volumes:
      - /mnt/hdd1/syncthing:/config
      - /mnt/hdd1/sync-data:/sync-data
    ports:
      - 22000:22000
      - 21027:21027/udp

  bitwarden:
    image: bitwardenrs/server:aarch64
    networks:
      front:
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
    volumes:
      - /mnt/hdd1/bw-data:/data
    ports:
      - 3012:3012

  ffsync:
    image: syncserver
    networks:
      front:
    environment:
      - SYNCSERVER_PUBLIC_URL=https://ffsync.ivan.build
      - SYNCSERVER_SECRET=${FFSYNC_SECRET}
      - SYNCSERVER_SQLURI=sqlite:////data/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - SYNCSERVER_ALLOW_NEW_USER=true
      - PORT=5000
    volumes:
      - /mnt/hdd1/ffsync-data/:/data
    ports:
      - 5000

  wikijs-db:
    image: postgres:11-alpine
    networks:
      wikijs-internal:
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: ${WIKIJS_DB_PASS}
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /mnt/hdd1/wikijs-data:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:2.2-arm
    depends_on:
      - wikijs-db
    networks:
      wikijs-internal:
      front:
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikijs-db
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_PASS=${WIKIJS_DB_PASS}
      - DB_NAME=wikijs
    volumes:
      - /mnt/hdd1/wikijs-data/file-backups:/file-backups

networks:
  front:
  wikijs-internal: