version: "3.3"

services:
  nginx:
    image: nginx
    depends_on:
      - bitwarden
      - nextcloud
      - portainer
      - silverstrike
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
    ports:
      - 80:80
      - 443:443

  silverstrike:
    image: simhnna/silverstrike
    depends_on:
      - silverstrike-db
    environment:
      ALLOWED_HOSTS: '*'
      DATABASE_URL: postgres://${SILVERSTRIKE_DB_USER}:${SILVERSTRIKE_DB_PASS}@silverstrike-db/${SILVERSTRIKE_DB_NAME}
      SECRET_KEY: ${SILVERSTRIKE_SECRET_KEY}

  silverstrike-db:
    image: postgres:10.3
    environment:
      POSTGRES_DB: ${SILVERSTRIKE_DB_NAME}
      POSTGRES_USER: ${SILVERSTRIKE_DB_USER}
      POSTGRES_PASSWORD: ${SILVERSTRIKE_DB_PASS}
    volumes:
      - silverstrike-db:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:2.1.1
    expose:
      - 9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  bitwarden:
    image: bitwardenrs/server:1.19.0
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: ${BW_ADMIN_TOKEN}
    expose:
      - 80
      - 3012
    volumes:
      - bw-data:/data

  nextcloud:
    image: nextcloud:20.0.7-apache
    depends_on:
      - nextcloud-db
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASS}
      POSTGRES_HOST: nextcloud-db
      NEXTCLOUD_DATA_DIR: /userdata
    volumes:
      - nextcloud-config:/var/www/html
      - nextcloud-userdata:/userdata
      - /etc/localtime:/etc/localtime:ro

  nextcloud-db:
    image: postgres:10.3
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASS}
    volumes:
      - silverstrike-db:/var/lib/postgresql/data

volumes:
  bw-data:
  nextcloud-config:
  nextcloud-userdata:
  portainer-data:
  silverstrike-db:
