version: "3.3"

services:
  nginx:
    image: nginx
    depends_on:
      - bookstack
      - silverstrike
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
    ports:
      - 80:80
      - 443:443

  bookstack:
      image: linuxserver/bookstack
      depends_on:
        - bookstack-db
      environment:
        APP_URL: https://notes.ivan.build
        PUID: 1000
        PGID: 1000
        DB_HOST: bookstack-db
        DB_USER: ${BOOKSTACK_DB_USER}
        DB_PASS: ${BOOKSTACK_DB_PASS}
        DB_DATABASE: ${BOOKSTACK_DB_NAME}
      volumes:
      - /opt/bookstack-data:/config

  bookstack-db:
    image: linuxserver/mariadb
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: ${BOOKSTACK_DB_PASS_ROOT}
      TZ: Europe/London
      MYSQL_DATABASE: ${BOOKSTACK_DB_NAME}
      MYSQL_USER: ${BOOKSTACK_DB_USER}
      MYSQL_PASSWORD: ${BOOKSTACK_DB_PASS}
    volumes:
      - /opt/bookstack-data:/config

  silverstrike:
    image: simhnna/silverstrike
    depends_on:
      - silverstrike-db
    environment:
      ALLOWED_HOSTS: '*'
      DATABASE_URL: postgres://${SILVERSTRIKE_DB_USER}:${SILVERSTRIKE_DB_PASS}@silverstrike-db/${SILVERSTRIKE_DB_NAME}
      SECRET_KEY: ${SILVERSTRIKE_SECRET_KEY}

  silverstrike-db:
    image: postgres:10.3
    environment:
      POSTGRES_DB: ${SILVERSTRIKE_DB_NAME}
      POSTGRES_USER: ${SILVERSTRIKE_DB_USER}
      POSTGRES_PASSWORD: ${SILVERSTRIKE_DB_PASS}
    volumes:
      - /opt/silverstrike-data:/var/lib/postgresql/data

  linkace:
    image: linkace/linkace:php-nginx
    depends_on:
      - linkace-db
    expose:
      - "8080"
    volumes:
      - ./.env-linkace:/app/.env
      - ./nginx-linkace.conf:/opt/docker/etc/nginx/conf.d/linkace.conf:ro
      - linkace_logs:/app/storage/logs

  linkace-db:
    image: bitnami/mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=${LINKACE_DB_PASS_ROOT}
      - MARIADB_USER=${LINKACE_DB_USER}
      - MARIADB_PASSWORD=${LINKACE_DB_PASS}
      - MARIADB_DATABASE=${LINKACE_DB_NAME}
    volumes:
      - db:/bitnami

volumes:
  linkace_logs:
  db:
    driver: local