version: "3.7"

services:
  nginx:
    image: nginx
    networks:
      - ivan-vps
    volumes:
      - le-certificates:/etc/nginx/certs
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    image: linuxserver/letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=ivan.build
      - SUBDOMAINS=sync,pass,mail
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=${LE_EMAIL}
    volumes:
      - ./cloudflare.ini:/config/dns-conf/cloudflare.ini
      - le-certificates:/config/etc/letsencrypt

  syncthing:
    image: linuxserver/syncthing:v1.4.0-ls28
    container_name: syncthing
    networks:
      ivan-vps:
        aliases:
          - syncthing
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
      UMASK_SET: "022"
    volumes:
      - ~/Sync:/config
      - /data1:/data1
      - /data2:/data2
    ports:
      - 22000:22000
      - 21027:21027/udp

  bitwarden:
    image: bitwardenrs/server
    networks:
      ivan-vps:
        aliases:
          - bitwarden
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
    volumes:
      - ~/bw-data:/data
    ports:
      - 3012:3012

networks:
  ivan-vps:

volumes:
  le-certificates:
    driver: local
    driver_opts:
      type: nfs
      o: bind
      device: /config/etc/letsencrypt